#ifndef _XBOX_COMPAT_WINHTTP_H
#define _XBOX_COMPAT_WINHTTP_H

#include <xtl.h>

typedef void* HINTERNET;
typedef DWORD_PTR INTERNET_SCHEME;

#define WINHTTP_FLAG_SECURE 0x00800000
#define WINHTTP_ADDREQ_FLAG_ADD 0x20000000
#define WINHTTP_OPTION_SECURITY_FLAGS 31
#define WINHTTP_ACCESS_TYPE_DEFAULT_PROXY 0
#define WINHTTP_NO_PROXY_NAME NULL
#define WINHTTP_NO_PROXY_BYPASS NULL
#define WINHTTP_NO_REFERER NULL
#define WINHTTP_DEFAULT_ACCEPT_TYPES NULL
#define WINHTTP_NO_ADD_HEADERS 0
#define WINHTTP_OPTION_REDIRECT_POLICY 0

typedef struct {
    DWORD dwMajorVersion;
    DWORD dwMinorVersion;
} WINHTTP_VERSION_INFO;

HINTERNET WINAPI WinHttpOpen(LPCWSTR, DWORD, LPCWSTR, LPCWSTR, DWORD);
HINTERNET WINAPI WinHttpConnect(HINTERNET, LPCWSTR, INTERNET_PORT, DWORD);
HINTERNET WINAPI WinHttpOpenRequest(HINTERNET, LPCWSTR, LPCWSTR, LPCWSTR, LPCWSTR, LPCWSTR*, DWORD);
BOOL WINAPI WinHttpSendRequest(HINTERNET, LPCWSTR, DWORD, LPVOID, DWORD, DWORD, DWORD_PTR);
BOOL WINAPI WinHttpReceiveResponse(HINTERNET, LPVOID);
BOOL WINAPI WinHttpQueryDataAvailable(HINTERNET, LPDWORD);
BOOL WINAPI WinHttpReadData(HINTERNET, LPVOID, DWORD, LPDWORD);
BOOL WINAPI WinHttpCloseHandle(HINTERNET);
BOOL WINAPI WinHttpAddRequestHeaders(HINTERNET, LPCWSTR, DWORD, DWORD);
BOOL WINAPI WinHttpSetOption(HINTERNET, DWORD, LPVOID, DWORD);
BOOL WINAPI WinHttpSetTimeouts(HINTERNET, int, int, int, int);

#endif
