#ifndef XUI_UI_H
#define XUI_UI_H

#include <windows.h>
#include <d3d9.h>

// XUI integration layer for Xbox 360.
// Implements an on-screen keyboard session driven by the host app's frame loop,
// based on the Atlas XuiKeyboard sample (XUI 1.0 runtime).

#ifdef __cplusplus
extern "C" {
#endif

// Initialize/release the XUI runtime and shared D3D device.
// Must be called after the D3D device is created and before rendering XUI.
BOOL xui_ui_init(IDirect3DDevice9* pDevice, D3DPRESENT_PARAMETERS* pPresent);

// Release all XUI resources. Must be called before releasing the D3D device.
void xui_ui_shutdown(void);

// Begin a new on-screen keyboard session with the given title and initial text
// (UTF-8). Returns FALSE if a session is already active or XUI is not ready.
BOOL xui_ui_keyboard_begin(const char* title, const char* default_text);

// Poll the active keyboard session. Call once per frame.
// Returns:
//    0  -> session still active; caller should feed input + render.
//    1  -> user pressed OK; out_utf8 (UTF-8) contains the entered text.
//   -1  -> user cancelled with B.
// Between frames call xui_ui_feed_input() and xui_ui_render().
int xui_ui_keyboard_poll(char* out_utf8, int out_utf8_size);

// Feed one frame of controller input to XUI. Call each frame while active.
void xui_ui_feed_input(void);

// Render the XUI overlay. Call after the app has drawn its 3D scene and
// before Present.
void xui_ui_render(DWORD dwBackWidth, DWORD dwBackHeight, float fDeltaTimeSeconds);

// ---------------------------------------------------------------------------
// Chrome overlay scenes (toolbar / settings / home). These are XUI scenes that
// run in a modal session driven by the platform, analogous to the keyboard.
// ---------------------------------------------------------------------------
typedef enum XuiChromeMode {
    XUI_CHROME_OFF = 0,
    XUI_CHROME_TOOLBAR,    // top navigation/toolbar bar
    XUI_CHROME_SETTINGS,   // settings panel
    XUI_CHROME_HOME        // home page
} XuiChromeMode;

// Actions generated by chrome scenes, mapped by the host to browser calls.
typedef enum XuiChromeAction {
    XUI_ACTION_NONE = 0,
    XUI_ACTION_BACK,
    XUI_ACTION_FORWARD,
    XUI_ACTION_REFRESH,
    XUI_ACTION_HOME,
    XUI_ACTION_NEW_TAB,
    XUI_ACTION_SETTINGS,
    XUI_ACTION_URL,        // open the URL text entered in the toolbar box
    XUI_ACTION_SEARCH,     // open the search text entered in the home box
    XUI_ACTION_LINK0,      // home quick links
    XUI_ACTION_LINK1,
    XUI_ACTION_LINK2,
    XUI_ACTION_LINK3,
    XUI_ACTION_HOMEPAGE_DEFAULT,
    XUI_ACTION_HOMEPAGE_NETXBOX,
    XUI_ACTION_HOMEPAGE_DUCKDUCKGO,
    XUI_ACTION_TOGGLE_TOOLBAR,
    XUI_ACTION_CLOSE
} XuiChromeAction;

// Enter a chrome session for the given mode. Renders that scene as a modal
// overlay. Returns FALSE if another session is already active.
BOOL xui_ui_chrome_begin(XuiChromeMode mode);

// Poll the active chrome session. Returns 0 while active; nonzero when the
// user dismissed it (B or a close action). Between frames call
// xui_ui_feed_input() and xui_ui_render().
int xui_ui_chrome_poll(void);

// Pop the next queued chrome action (0 if none). Call after chrome_poll
// returns nonzero and before/while draining.
int xui_ui_chrome_take_action(void);

// Set the text in the toolbar URL box.
void xui_ui_chrome_set_url(const char* url);

// Set whether the toolbar chrome is currently drawn as a persistent strip.
void xui_ui_chrome_set_toolbar_visible(BOOL visible);

#ifdef __cplusplus
}
#endif

#endif // XUI_UI_H
